# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1457268096352915f3aad9ec6cfcdca14bba7f2213479c7734e13eb94ab7b454e3a8e79f910f72e138fb60a210b97c15df816ae3f01bdc6d1793070f1546b214

test:
  secret_key_base: f585bc47dcd524e23551f98aceac72241d235d2e9b023a52f06a1e1bf6a1fedcd9c0602c051c49c80ca06d1c336db03b3bad64a066c6faf95791d8300f118fef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
